### ISSUE TITLE
small overhead

### ISSUE THREAD

**Issue by vseledkin** [DataWraith/vptree#2]
In line https://github.com/DataWraith/vptree/blob/master/vptree.go#L108 unnecessary expensive distance 
calculation 
change 
n.Threshold = vp.distanceMetric(items[median], n.Item)
to
n.Threshold = pivotDist

**Comment by DataWraith** [comment]
Hi. Thanks for reporting this. :+1:  Sorry for the late reply; I was on vacation.

Do you want to make a quick pull request, or do you want me to fix it? I've seen people with either preference, so I thought I'd ask first.

Cheers,
DataWraith

**Comment by vseledkin** [comment]
actually i have my own implementation and i just compared my version and yours for correctness :)
by the way where is cool advancement related to hight dimensional metric space indexing google for "Annoy" if you curious about

**Comment by DataWraith** [comment]
The spotify one? I'll look into it.

That you don't use the project yourself directly makes it even more awesome that you took the time to submit this issue. Thanks again!
